image: node:lts-bullseye-slim

include: 
  - template: Container-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main"
    - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - lint
  - build
  - docker-build
  - test
  - release
  - deploy

default:
  cache:  # Cache modules in between jobs for the same branch if package-lock.json file changes
    key: 
      prefix: $CI_COMMIT_REF_NAME
      files:
        - ./WeatherWreck/server/package-lock.json
        - ./WeatherWreck/client/package-lock.json
    paths:
      - ./WeatherWreck/server/.npm/
      - ./WeatherWreck/client/.npm
  # run this before every job; will hit the cache first
  before_script:
   - cd ./WeatherWreck/server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..
   
install:
  stage: build
  script:
    # Tell npm to cache modules in ./.npm (default is ~/.npm but when running a script
    # in GitLab CI we need to keep everything is the project root)
    # npm ci stands for "clean install" and it relies on package-lock.json. 
    # It is often used in automation to
    # make sure we create a reproducible testing environment (no stale dependencies from previous jobs)
    # The --prefer-offline option makes npm avoid fetching a module from the package repository
    # unless it's missing from the cache
    - ls -la
    - cd server && npm ci --cache .npm --prefer-offline
  # Cache modules in between jobs to avoid re-downloading them
  # https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
  cache:  
    # Look up the cache by the commit ref (i.e. only jobs for same commit share cache)
    key: $CI_COMMIT_REF_SLUG
    paths:
      # The path to cache
      - .npm/
  # set `node_modules` as an artifact so that the test job can use it
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

lint-server:
  stage: lint 
  script:
    - ls -la
    - cd server && ./node_modules/eslint/bin/eslint.js . 
  allow_failure: false

lint-client:
  stage: lint 
  script:
    - ls -la
    - cd client && ./node_modules/eslint/bin/eslint.js .
  allow_failure: false
  
server-test:
    stage: test
    # Specify that this job only uses artifacts from the install job
    dependencies:
        - install
    script: 
        - cd server && npm run test  

# Unfortunetlty we were trying to run it only on staging but coudn't make it work, since CI_COMMIT_BRANCH just dind't have any value.
build-frontend:
  stage: build
  script:
    - cd client && npm run build 
    - cd ..
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - WeatherWreck/client/dist

# Same problem as build-frontend.
build-app-archive:
  stage: release
  variables:
    RELEASE_FILE: release-$CI_PROJECT_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA.tar.gz
  dependencies:
    - build-frontend
  rules:
    - if: $CI_COMMIT_TAG 
  before_script:
    - cd WeatherWreck/server
    - npm ci --omit=dev
  script:
    - cd ..
    - tar -zcvf $RELEASE_FILE server/node_modules server/bin/www.js server/controllers/ server/db/db.mjs server/routers/ server/api.mjs client/dist server/package.json server/package-lock.json
  artifacts:
    expire_in: 7 days
    name: $RELEASE_FILE
    paths:
      - WeatherWreck/$RELEASE_FILE

# Infortunetly we had to put bundlesize-check into Release stage because by putting it in the build stage it was executing before the 
# build-frontend job, thus preventing us from using it's artifact (client/dist). We had to move it into Release stage then to ensure, 
# the artifact will be present before this job runs !
bundlesize-check:
  stage: release
  dependencies:
    - build-frontend
  script:
    - cd client/dist
    - npm run bundlesize 


server-image:
  stage: docker-build
  image: docker:28.0.0
  # dind starts the docker daemon so we can use docker commands
  services:
    - docker:28.0.0-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG     
  rules:
    - if: ($CI_COMMIT_BRANCH == "docker-sec" || $CI_COMMIT_BRANCH == "docker-review" || $CI_COMMIT_BRANCH == "main")
  before_script:
    - cd ./WeatherWreck/server
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin 
    - docker build -t $IMAGE_TAG -f server.Dockerfile .    
    - docker push $IMAGE_TAG

container_scanning:
  extends: .container_scanning
  variables: 
    CS_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

